CREATE TABLE [staging].[sysjobs_UPDATE]
(
	[ETL_KEY]		INT NOT NULL 
,	[STAGING_KEY]	INT	NOT NULL
,	[ACTION]		CHAR(1)	NOT NULL
		CONSTRAINT CK_sysjobs_UPDATE_ACTION
			CHECK ([ACTION] IN ( 'I', 'U', 'D'))
,	[JOB_KEY]		INT NULL
,	[job_id]		UNIQUEIDENTIFIER NOT NULL
)
