CREATE PROCEDURE [dbo].[CALCULATE_JOB_STEP_AVERAGE_DURATION]
AS
BEGIN
	/*
		Calculate the average duration for jobs from the [dbo].[JOB_STEP_DURATION] table.
	*/

	TRUNCATE TABLE [dbo].[JOB_STEP_AVERAGE_DURATION];

	;WITH CTE_SUM_DURATION AS (
		SELECT 
			[JOB_KEY]					
		,	[step_id]					
		,	SUM([JOB_STEP_COUNT])			[TOTAL_STEP_COUNT]
		,	SUM([JOB_STEP_TOTAL_SECONDS])	[TOTAL_STEP_DURATION]
		FROM [dbo].[JOB_STEP_DURATION] 
		GROUP BY [JOB_KEY],	[step_id]
	)

	INSERT [dbo].[JOB_STEP_AVERAGE_DURATION] (
		[JOB_KEY]					
	,	[step_id]					
	,	[TOTAL_STEP_COUNT]			
	,	[TOTAL_STEP_DURATION]		
	,	[AVERAGE_STEP_DURATION]		
	)

	SELECT
		[JOB_KEY]					
	,	[step_id]					
	,	[TOTAL_STEP_COUNT]
	,	[TOTAL_STEP_DURATION]
	,	IIF(ISNULL([TOTAL_STEP_COUNT], 0) > 0
		,	[TOTAL_STEP_DURATION] / [TOTAL_STEP_COUNT]
		,	NULL
		)	AS [AVERAGE_STEP_DURATION]
	FROM CTE_SUM_DURATION
END
