CREATE PROCEDURE [dbo].[CLOSE_ETL_HISTORY_LOG]
	@P_ETL_KEY	INT	= NULL
AS
BEGIN
	DECLARE
		@ETL_KEY	INT;

	IF @P_ETL_KEY IS NULL
	BEGIN
		SELECT
			@ETL_KEY = MAX([ETL_KEY])
		FROM [dbo].[ETL_HISTORY_LOG];
	END
	ELSE
	BEGIN
		 SET @ETL_KEY = @P_ETL_KEY;
	END

	UPDATE [dbo].[ETL_HISTORY_LOG]
	SET
		[END_DATE] = GETDATE()
	WHERE [ETL_KEY] = @ETL_KEY;
END
