CREATE PROCEDURE [dbo].[GET_ETL_HISTORY_LOG]
	@P_ETL_KEY				INT OUTPUT
,	@P_BEGIN_INSTANCE_ID	INT OUTPUT
,	@P_END_INSTANCE_ID		INT OUTPUT
AS
BEGIN
	/*
		Get the row created by the last execution of [dbo].[CREATE_ETL_HISTORY_LOG] which
		should be the first step in the SQL Agent job. 

		Steps following the first step that need the @ETL_KEY should call this procedure.

		USAGE:

		DECLARE 
			@ETL_KEY			INT
		,	@BEGIN_INSTANCE_ID	INT
		,	@END_INSTANCE_ID	INT;

		EXEC [dbo].[GET_ETL_HISTORY_LOG]
			@P_ETL_KEY = @ETL_KEY OUTPUT
		,	@P_BEGIN_INSTANCE_ID = @BEGIN_INSTANCE_ID	OUTPUT
		,	@P_END_INSTANCE_ID = @END_INSTANCE_ID		OUTPUT;

		SELECT 
			@ETL_KEY
		,	@BEGIN_INSTANCE_ID
		,	@END_INSTANCE_ID;

	*/
	DECLARE 
		@ETL_KEY	INT
	,	@BEGIN_INSTANCE_ID	INT
	,	@END_INSTANCE_ID	INT;

	SELECT 
		@ETL_KEY = MAX([ETL_KEY]) 
	FROM [dbo].[ETL_HISTORY_LOG];

	SELECT
		@BEGIN_INSTANCE_ID = [BEGIN_INSTANCE_ID]
	,	@END_INSTANCE_ID   = [END_INSTANCE_ID]
	FROM [dbo].[ETL_HISTORY_LOG]
	WHERE [ETL_KEY] = @ETL_KEY;

	SET @P_ETL_KEY = @ETL_KEY;
	SET @P_BEGIN_INSTANCE_ID = @BEGIN_INSTANCE_ID;
	SET @P_END_INSTANCE_ID = @END_INSTANCE_ID;
END
