CREATE TABLE [dbo].[ACTIVE_JOBS]
(
	[REFRESH_KEY]			INT
,	[job_id]				UNIQUEIDENTIFIER
,	[CURRENT_DURATION]		INT				-- seconds
,	[EXECUTION_COUNT]		INT
,	[AVERAGE_DURATION]		INT				-- seconds
,	[ESTIMATED_COMPLETION]	SMALLDATETIME
	CONSTRAINT PK_ACTIVE_JOBS
		PRIMARY KEY CLUSTERED ([REFRESH_KEY], [job_id])
)
