CREATE TABLE [dbo].[ETL_LOG]
(
	[ETL_KEY]		INT		IDENTITY	NOT NULL 
		CONSTRAINT PK_ETL_LOG
			PRIMARY KEY CLUSTERED
,	[START_DATE]	SMALLDATETIME	NOT NULL
		CONSTRAINT DF_ETL_LOG_START_DATE
			DEFAULT GETDATE()
,	[MAX_SYSJOBHISTORY_INSTANCE_ID]	INT NULL
,	[END_DATE]		SMALLDATETIME	NULL
,	[RESULT_CODE]	INT				NULL
)
