CREATE TABLE [dbo].[JOB_STEP_AVERAGE_DURATION]
(
	[JOB_KEY]					INT 				NOT NULL
,	[step_id]					INT					NOT NULL
,	[TOTAL_STEP_COUNT]			INT
,	[TOTAL_STEP_DURATION]		INT
,	[AVERAGE_STEP_DURATION]		INT
	CONSTRAINT PK_JOB_STEP_AVERAGE_DURATION
		PRIMARY KEY CLUSTERED ([JOB_KEY], [step_id])
)
