CREATE TABLE [staging].[sysjobsteps](
	[job_id] [uniqueidentifier] NULL,
	[step_id] [int] NULL,
	[step_name] [nvarchar](128) NULL,
	[subsystem] [nvarchar](40) NULL,
	[command] [nvarchar](max) NULL,
	[flags] [int] NULL,
	[additional_parameters] [nvarchar](max) NULL,
	[cmdexec_success_code] [int] NULL,
	[on_success_action] [tinyint] NULL,
	[on_success_step_id] [int] NULL,
	[on_fail_action] [tinyint] NULL,
	[on_fail_step_id] [int] NULL,
	[server] [nvarchar](128) NULL,
	[database_name] [nvarchar](128) NULL,
	[database_user_name] [nvarchar](128) NULL,
	[retry_attempts] [int] NULL,
	[retry_interval] [int] NULL,
	[os_run_priority] [int] NULL,
	[output_file_name] [nvarchar](200) NULL,
	[last_run_outcome] [int] NULL,
	[last_run_duration] [int] NULL,
	[last_run_retries] [int] NULL,
	[last_run_date] [int] NULL,
	[last_run_time] [int] NULL,
	[proxy_id] [int] NULL,
	[step_uid] [uniqueidentifier] NULL,
	--[ETL_RUN_KEY]	BIGINT NOT NULL,
	[STAGING_KEY] [int] IDENTITY(1,1) NOT NULL
) 
